"""
Push a Tucker-compressed model to Hugging Face Hub.

Usage:
    python hf_export/push_to_hub.py \
        --model-path ./compressed_model \
        --repo-id your-username/gpt2-tucker-r64 \
        --original-model gpt2 \
        --rank 64
"""

from __future__ import annotations
import argparse
import json
import os
from pathlib import Path


def build_model_card(
    original_model: str,
    rank: int,
    speedup: float,
    perplexity_delta: float,
) -> str:
    """Build a model card string for HuggingFace Hub."""
    return f"""---
language: en
license: mit
tags:
  - latency-surgeon
  - tucker-decomposition
  - model-compression
  - inference-optimization
base_model: {original_model}
---

# {original_model} — Tucker Compressed (rank={rank})

This model was compressed with [LatencySurgeon](https://github.com/your-org/latency-surgeon)
using Tucker decomposition on all attention projection layers.

## Performance

| Metric | Value |
|:-------|------:|
| Speedup vs baseline | **{speedup:.2f}×** |
| Perplexity delta | +{perplexity_delta:.3f} |
| Tucker rank | {rank} |
| Compressed layers | q/k/v/o projections |

## Usage

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from latency_surgeon.hf_integration import load_compressed_model

model, tokenizer = load_compressed_model("{original_model}", rank={rank})
inputs = tokenizer("Hello, world!", return_tensors="pt")
outputs = model.generate(**inputs, max_new_tokens=50)
print(tokenizer.decode(outputs[0]))
```

## How It Works

Tucker decomposition replaces each attention weight matrix W ∈ R^{{m×n}} with two
smaller matrices: Linear(m, r) + Linear(r, n), where r={rank} << min(m,n).

This reduces FLOPs from O(m·n) to O(r(m+n)) per matrix-vector product.

## Generated by

🏥 [LatencySurgeon](https://github.com/your-org/latency-surgeon) —
Built with [NEO](https://neo.anthropic.com)
"""


def push_to_hub(
    model_path: str,
    repo_id: str,
    original_model: str,
    rank: int,
    speedup: float = 1.4,
    perplexity_delta: float = 0.03,
    token: str | None = None,
) -> str:
    """Push compressed model to Hugging Face Hub.

    Args:
        model_path: Local path to saved compressed model.
        repo_id: HuggingFace repo id, e.g. "username/model-name".
        original_model: Original model name, e.g. "gpt2".
        rank: Tucker rank used for compression.
        speedup: Measured speedup factor.
        perplexity_delta: Measured perplexity increase.
        token: HuggingFace token (or set HF_TOKEN env var).

    Returns:
        URL of the pushed repository.
    """
    try:
        from huggingface_hub import HfApi, upload_folder, create_repo
    except ImportError:
        raise ImportError("huggingface_hub is required: pip install huggingface_hub")

    token = token or os.environ.get("HF_TOKEN")
    api = HfApi(token=token)

    print(f"Creating/getting repo: {repo_id}")
    create_repo(repo_id, exist_ok=True, token=token)

    # Write model card
    model_card = build_model_card(original_model, rank, speedup, perplexity_delta)
    card_path = Path(model_path) / "README.md"
    card_path.write_text(model_card, encoding="utf-8")

    # Write surgery config
    config = {
        "original_model": original_model,
        "tucker_rank": rank,
        "latency_surgeon_version": "0.1.0",
        "speedup_factor": speedup,
        "perplexity_delta": perplexity_delta,
    }
    config_path = Path(model_path) / "surgery_config.json"
    config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")

    print(f"Uploading {model_path} → {repo_id}")
    url = upload_folder(
        folder_path=model_path,
        repo_id=repo_id,
        repo_type="model",
        token=token,
        commit_message=f"Upload Tucker-compressed {original_model} (rank={rank})",
    )
    print(f"Uploaded to: https://huggingface.co/{repo_id}")
    return f"https://huggingface.co/{repo_id}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Push Tucker-compressed model to HF Hub")
    parser.add_argument("--model-path", required=True, help="Local path to compressed model")
    parser.add_argument("--repo-id", required=True, help="HuggingFace repo id")
    parser.add_argument("--original-model", default="gpt2", help="Original model name")
    parser.add_argument("--rank", type=int, default=64, help="Tucker rank used")
    parser.add_argument("--speedup", type=float, default=1.4, help="Measured speedup")
    parser.add_argument("--perplexity-delta", type=float, default=0.03)
    parser.add_argument("--token", default=None, help="HuggingFace token")
    args = parser.parse_args()

    url = push_to_hub(
        model_path=args.model_path,
        repo_id=args.repo_id,
        original_model=args.original_model,
        rank=args.rank,
        speedup=args.speedup,
        perplexity_delta=args.perplexity_delta,
        token=args.token,
    )
    print(f"\nDone! Model available at: {url}")


if __name__ == "__main__":
    main()
